# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - chatbotflaskapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Create and activate virtual environment
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      # Step 5: Zip artifact for deployment
      - name: Zip artifact for deployment
        run: zip -r release.zip . -x './venv/*'

      # Step 6: Upload artifact for deployment jobs
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write  # Required for requesting the JWT

    steps:
      # Step 7: Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 8: Unzip artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step 9: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{  secrets.AZUREAPPSERVICE_CLIENTID_BBBBB9E6F21E4CDDA995450F780F8D42 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D22B77E34CF849108701A7027B155E09 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_838C38B662BC45AAA22AF9C03749C0F8 }}

      # Step 10: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'chatbotflaskapi'
          slot-name: 'Production'  # Omit if not using slots
          package: ./
